version: '3'
services:
  test:
    build:
      context: .
      target: builder
    command:
      - sh
      - -c
      - go test -v ./...
    environment:
      REDIS_HOST: redis:6379
    depends_on: [ redis ]

